//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hurtowniaEntities : DbContext
    {
        public hurtowniaEntities()
            : base("name=hurtowniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        

        public virtual DbSet<Do_zamowienia> Do_zamowienia { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<Magazyny> Magazyny { get; set; }
        public virtual DbSet<Platnosc> Platnosc { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<Zamowienia_klientow> Zamowienia_klientow { get; set; }
        public virtual DbSet<Produkty_Do_zamowienia> Produkty_Do_zamowienia { get; set; }
        public virtual DbSet<Produkty_Magazyn> Produkty_Magazyn { get; set; }
        public virtual DbSet<Produkty_Zamowienia_klientow> Produkty_Zamowienia_klientow { get; set; }
    }
}
