//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platnosc
    {
        public int id_platnosci { get; set; }
        public System.DateTime data_platnosci { get; set; }
        public int id_zamowienia { get; set; }
        public string rodzaj_platnosci { get; set; }

        internal virtual Zamowienia_klientow Zamowienia_klientow { get; set; }
    }
}
