//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty_Zamowienia_klientow
    {
        public int id_produktu { get; set; }
        public int id_zamowienia { get; set; }
        public Nullable<int> ilosc { get; set; }
    
        public virtual Produkty Produkty { get; set; }
        public virtual Zamowienia_klientow Zamowienia_klientow { get; set; }
    }
}
